- package-lock.json
- package.json
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/greet/greet.page.html
- src/app/greet/greet.page.ts
- src/app/services/auth/auth.service.spec.ts
- src/app/services/auth/auth.service.ts
auth0 set up and login button hooked up to auth0 login function
> Auth0 setup

- database/database.js
- package-lock.json
- server/apiHelpers.js
- server/server.js
> created post to signup

- database/database.js
- server/server.js
- src/app/api.service.ts
- src/app/profile/profile.page.html
- src/app/profile/profile.page.ts
Client sends user info to server for signup. Server can send info to client.
> Profile dynamically displaying username

- server/server.js
- src/app/api.service.ts
- src/app/app.module.ts
- src/app/footer/footer.component.html
- src/app/footer/footer.component.ts
- src/app/modals/modals.component.ts
- src/app/modals/modals.module.ts
- src/app/search_modal/search_modal.component.html
- src/app/search_modal/search_modal.component.ts
- src/app/search_modal/search_modal.module.ts
search modal with search bar
onclick of search button, successful get req to server --> db helper function still needs to be made
onclick of search button, redirects to matches page and closes modal
> Search modal

- src/app/modals/modals.component.html
- src/app/modals/modals.component.ts
- src/app/modals/modals.module.ts
- src/app/services/settings/settings.service.ts
- src/app/want_list_modal/want_list_modal.component.ts
successfully sending data from inputs
> Settings now connected to paired functions

- server/server.js
- src/app/app.module.ts
- src/app/modals/modals.component.html
- src/app/modals/modals.component.ts
- src/app/services/autoComplete/auto-complete.service.spec.ts
- src/app/services/autoComplete/auto-complete.service.ts
- src/app/services/settings/settings.service.ts
Autocomplete fully implemented
> Autocomplete

- server/server.js
- src/app/profile/profile.page.html
- src/app/services/auth/auth.service.ts
> Profile loads user specific information

- src/app/home/home.page.html
- src/app/home/home.page.ts
pressing profile button gets user info
> listings info

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/home/home.page.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.module.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.html
- src/app/profile/peerProfile/peer-profile/peer-profile.page.spec.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
User can visit other's profiles
> Peer profiles

- server/server.js
- src/app/api.service.ts
- src/app/home/home.page.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.html
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
- src/app/profile/profile.page.html
Sends query to database on peer profile load
> peer profile retrieves info on init

- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
Dynamically gets all books for all users
> users books

- server/server.js
- src/app/home/home.page.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.html
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
- src/app/profile/profile.page.html
- src/app/profile/profile.page.ts
- src/app/services/auth/auth.service.ts
got rid of offers list
added offers list back to user profile
want list rendering correctly
listing list still strugglin
> peer profile

- server/server.js
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
listings are now books instead of join table info
> Peer info successfully displays

- server/server.js
- src/app/api.service.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
- src/app/profile/profile.page.ts
> offers are sent to user

- database/Listing.js
- database/Offer.js
- database/School.js
- database/Want.js
- server/server.js
- src/app/profile/profile.page.ts
database tables altered, want - fulfilled, listing - available, schooll - name, offers - money exchange cents
> database changes

- database/Contact_Us.js
- database/User.js
- server/server.js
- src/app/modals/modals.component.html
- src/app/modals/modals.component.ts
endpoint to /user/settings now have toasts on submission
table contact us adjusted
> /user/settings, toasts, table adjustment

- package-lock.json
- src/app/add_listing_modal/add_listing_modal.component.html
- src/app/home/home.page.html
- src/app/modals/modals.component.html
- src/app/profile/peerProfile/peer-profile/peer-profile.page.html
- src/app/profile/profile.page.html
- src/app/search_modal/search_modal.component.html
- src/app/want_list_modal/want_list_modal.component.html
- src/global.scss
styling still needs a lot of work but has feedback and more visable
> blue buttons

- database/Book.js
- database/User.js
- database/Want.js
- package-lock.json
- server/apiHelpers.js
- server/server.js
- src/app/api.service.ts
- src/app/chat/chat.page.html
- src/app/profile/profile.page.ts
- src/index.html
added image_link to want and book table, 
changed link_image to image_link in user table
document.getElementById('searchInput').textContent changed to 
document.getElementById('searchInput').value
> table additions, images

- package-lock.json
- package.json
- server/server.js
- src/app/api.service.ts
- src/app/home/home.page.html
- src/app/home/home.page.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
- src/index.html
Peer profiles now have correct id's
Opening scanner no longer causes error
> Fixed a couple of bugs

- server/server.js
- src/app/footer/footer.component.ts
- src/app/home/home.module.ts
Users can now see multiple offers to any of their listings
> Multiple offers can be made on the same listing

- package-lock.json
- server/server.js
- src/app/profile/profile.page.html
- src/app/profile/profile.page.ts
accept button changes status in db and on profile view
> Accept button

- server/server.js
- src/app/api.service.ts
- src/app/profile/profile.page.ts
> Tomtom frame created

- package-lock.json
- server/server.js
- src/app/api.service.ts
- src/app/home/home.page.ts
- src/app/profile/profile.page.ts
> tomtom returning data

- server/server.js
- tslint.json
replaced all console log with relevant status code and corresponding message
> Linted server.js

- server/server.js
- src/app/profile/peerProfile/peer-profile/peer-profile.page.html
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
- src/app/profile/profile.page.html
- src/app/profile/profile.page.ts
sending money from offer to server + bug fix for displaying offers to profile
> Moneyxchange

- server/server.js
- src/app/api.service.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
saving multiple listings to db successfully
> endpoint to /offers working successfully and saving to db

- server/server.js
- src/app/api.service.ts
- src/app/home/home.page.ts
> Tomtom works!!!

- server/server.js
- src/app/chat.service.ts
- src/app/home/home.page.ts
- src/app/web-socket-service.service.spec.ts
- src/app/web-socket-service.service.ts
- src/index.html
fixed bug with old socket code
> Matches filtered by school

- src/app/profile/profile.page.html
- src/app/profile/profile.page.ts
Pending and Accepted offers rendering on user profile
> Offers update

- src/app/api.service.ts
- src/app/chat/chat.page.ts
- src/app/profile/profile.page.ts
- src/app/services/settings/settings.service.ts
> Url switch

- src/app/api.service.ts
- src/app/chat/chat.page.ts
- src/app/counter_offer_modal/counter_offer_modal.component.html
- src/app/counter_offer_modal/counter_offer_modal.component.ts
- src/app/home/home.page.html
- src/app/home/home.page.ts
- src/app/modals/modals.component.ts
- src/app/profile/profile.page.html
- src/app/profile/profile.page.ts
- src/app/services/auth/auth.service.ts
- src/app/services/settings/settings.service.ts
- src/environments/environment.ts
> Counter offer modal now has dropdowns

- src/app/chat/chat.page.html
- src/app/chat/chat.page.ts
> Chat fixed

- server/server.js
- src/app/chat.service.ts
- src/app/chat/chat.page.ts
- src/app/counter_offer_modal/counter_offer_modal.component.ts
- src/app/profile/peerProfile/peer-profile/peer-profile.page.html
- src/app/profile/peerProfile/peer-profile/peer-profile.page.ts
- src/app/profile/profile.page.ts
Cleaned up a couple of functions and fixed the offer repeat bug.
Also sending more info on offer accept.
Prep for automating chat: significant progress
> destructuring fixed bugs

- src/app/profile/profile.page.html
- src/app/profile/profile.page.ts
- src/global.scss
still need: 
buttons to be same width
correct spacing
few other things
> Profile Page styling

- server/server.js
- src/app/app.module.ts
- src/app/chat.service.ts
- src/app/profile/profile.page.ts
- src/app/web-socket-service.service.spec.ts
- src/index.html
auto rejects all offers with a reference to an unavailable book
> books that are no longer available do not display

- src/app/profile/profile.page.ts
Offers now rerender when an offer is accepted.
> Fixed a slight bug

- src/app/api.service.ts
- src/app/chat.service.ts
- src/app/chat/chat.page.ts
- src/app/counter_offer_modal/counter_offer_modal.component.ts
- src/app/home/home.page.html
- src/app/home/home.page.ts
- src/app/profile/profile.page.ts
- src/app/services/auth/auth.service.ts
- src/app/services/settings/settings.service.ts
switched server references to deployed server.
> ready for deployment
